### PR TITLE
Allow to enable|disable existing incidents

### PR DESCRIPTION
**Pull request by willdurand**
New commands are:

```
hubot incident <id> enable
hubot incident <id> disable
```

### CODE REVIEW

**Comment by willdurand** [comment]
Hi @jbrooksuk! It would be nice to allow putting `visible: true|false` (incident API).

**Comment by jbrooksuk** [comment]
Hmm, you should actually be able to `POST` or `PUT` with `visible=true` etc. Looks like we're not documenting it though.

**Comment by willdurand** [comment]
@jbrooksuk I get a 400 error on `/incidents/<id>`. Did I miss anything?

**Comment by jbrooksuk** [comment]
@willdurand give me a few mins and I'll check :)

**Comment by jbrooksuk** [comment]
Ok, use `1` for true and `0` for false.

**Comment by willdurand** [comment]
@jbrooksuk oh you're right. Thank you! I did not deeply investigate..

**Comment by jbrooksuk** [comment]
@willdurand don't worry, the docs don't mention it. Just working on something then I'll update.

**Comment by willdurand** [comment]
The `400` was misleading actually :)

**Comment by jbrooksuk** [comment]
Unfortunately Cachet's API doesn't coerce `true` or `false` into `1` and `0` respectively. It's something that'd be good to do though.

**Pull request merged**
